# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sergiohidalgocaceres
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambda-sqs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-sqs

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: sqs:SendMessage
          Resource: arn:aws:sqs:us-east-1:282865065290:SQS_COURSE

build:
  esbuild:
    bundle: true
    minify: false
    exclude:
      - "@aws-sdk/*"
    sourcemap:
      type: linked

functions:
  source:
    handler: src/handlers/source/index.execute
    events:
      - http:
          path: /create
          method: post
    environment:
      SQS_URL: https://sqs.us-east-1.amazonaws.com/282865065290/SQS_COURSE

  destination:
    handler: src/handlers/destination/index.execute
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:282865065290:SQS_COURSE
