# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sergiohidalgocaceres
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: appointment
# "service" is the name of this project. This will also be added to your AWS resource names.
service: appointment

provider:
  name: aws
  stage: dev
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource: arn:aws:lambda:us-east-1:282865065290:function:*

build:
  esbuild:
    bundle: true
    minify: false
    exclude:
      - "@aws-sdk/*"
    sourcemap:
      type: linked

functions:
  appointment:
    handler: src/handlers/appointment/main.execute
    events:
      - http:
          path: /appointment
          method: post
    environment:
      APPOINTMENT_PE: ${self:service}-${self:provider.stage}-appointment-pe
      APPOINTMENT_EC: ${self:service}-${self:provider.stage}-appointment-ec
      APPOINTMENT_AR: ${self:service}-${self:provider.stage}-appointment-ar

  appointment-pe:
    handler: src/handlers/appointment-pe/main.execute
  appointment-ec:
    handler: src/handlers/appointment-ec/main.execute
  appointment-ar:
    handler: src/handlers/appointment-ar/main.execute
